Added XFS support

diff --git a/create b/create
--- a/create
+++ b/create
@@ -59,7 +59,19 @@ else
   exit 1
 fi
 
-mke2fs -Fjqt $OSP_FILESYSTEM $filesystem_dev
+case $OSP_FILESYSTEM in
+	ext2|ext3|ext4)
+		mke2fs -Fjqt $OSP_FILESYSTEM $filesystem_dev
+		;;
+	xfs)
+		mkfs.xfs -fq $filesystem_dev
+		;;
+	*)
+		echo "Invalid value '$OSP_FILESYSTEM' for the filesystem parameter" 1>&2
+		exit 1
+		;;
+esac
+
 root_uuid=$($VOL_ID $filesystem_dev )
 
 if [ -n "$swapdev" ]; then
diff --git a/export b/export
--- a/export
+++ b/export
@@ -41,12 +41,18 @@ fi
 
 vol_type=$($VOL_TYPE $filesystem_dev)
 
-if [ "${vol_type:0:3}" = "ext" ]; then
-  dump -0 -q -f - "$filesystem_dev"
-else
-  echo "Can't dump partition of type ${vol_type}!" >&2
-  exit 1
-fi
+case $vol_type in
+	ext*)
+		dump -0 -q -f - "$filesystem_dev"
+		;;
+	xfs)
+		xfsdump -l 0 -F - "$filesystem_dev"
+		;;
+	*)
+		echo "Can't dump partition of type ${vol_type}!" >&2
+		exit 1
+		;;
+esac
 
 # execute cleanups
 cleanup
